### ISSUE TITLE
Deny new registration fails in Firefox

### ISSUE THREAD

**Issue by petertambach** [LenticularCloud/Cloud-Ldap-Admin#5]
Tested on Firefox 47 & 48 on Linux.
When you want to deny a new user request, a popup comes up with "Please select an item from the list"

**Comment by TuxCoder** [comment]
Interessting bug, comes from the fact that deny is has the boolen value `False`
The form render software renders that as a emty value eg `<option .. value="" >..</option>`.
will take a look.

**Comment by TuxCoder** [comment]
should be fixed and online. Can you test it and close the issue if it works?

**Comment by petertambach** [comment]
Works.
